name: opbg # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: OPBG tools # 79 char long summary
description: |
  OPBG tools

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  nb-start:
    command: mri-notebook-start
  nb-stop:
    command: mri-notebook-stop
  nb-tf-start:
    command: mri-notebook-tf-start
  nb-token:
    command: mri-notebook-token
  
parts:
  mri:
    source: bin
    source-type: local
    plugin: dump
